# Generated by Django 4.0.3 on 2022-03-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pseudo', models.CharField(default='Choose an alias', max_length=10)),
                ('email', models.CharField(default='Add your e-mail here', max_length=35)),
                ('zipcode', models.IntegerField(default='Add your zip code')),
                ('bio', models.TextField(default='Add a bio', max_length=280)),
            ],
        ),
    ]
