# Generated by Django 4.0.2 on 2022-03-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furnitures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Bed', 'Bed'), ('Chair', 'Chair'), ('Table', 'Table'), ('Couch', 'Couch'), ('Closet', 'Closet')], default='Bed', max_length=10)),
            ],
        ),
    ]
