# Generated by Django 4.0.2 on 2022-03-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitures',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Grey', 'Grey'), ('Brown', 'Brown'), ('Yellow', 'Yellow')], default='Grey', max_length=10),
        ),
        migrations.AddField(
            model_name='furnitures',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Used', 'Used'), ('Old', 'Old')], default='Used', max_length=10),
        ),
        migrations.AddField(
            model_name='furnitures',
            name='material',
            field=models.CharField(choices=[('Wood', 'Wood'), ('Metal', 'Metal'), ('Plastic', 'Plastic'), ('Leather', 'Leather'), ('Wool', 'Wool')], default='Wood', max_length=10),
        ),
    ]
