# Generated by Django 4.0.3 on 2022-03-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_furnitures_color_furnitures_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitures',
            name='dimension',
            field=models.CharField(default='100x200x200', max_length=255),
        ),
        migrations.AddField(
            model_name='furnitures',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='furnitures',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
