# Generated by Django 4.0.3 on 2022-03-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_furnitures_dimension_furnitures_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnitures',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
