# Generated by Django 4.0.3 on 2022-03-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_furnitures_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitures',
            name='description',
            field=models.TextField(default='Add a description of your item here.'),
        ),
        migrations.AddField(
            model_name='furnitures',
            name='title',
            field=models.CharField(default='Add a title here.', max_length=255),
        ),
        migrations.AlterField(
            model_name='furnitures',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Grey', 'Grey'), ('Brown', 'Brown'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Red', 'Red'), ('Pink', 'Pink'), ('Green', 'Green')], default='Grey', max_length=10),
        ),
        migrations.AlterField(
            model_name='furnitures',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Like New', 'Like New'), ('Good', 'Good'), ('Used', 'Used'), ('Old', 'Old')], default='Used', max_length=10),
        ),
        migrations.AlterField(
            model_name='furnitures',
            name='material',
            field=models.CharField(choices=[('Wood', 'Wood'), ('Metal', 'Metal'), ('Plastic', 'Plastic'), ('Leather', 'Leather'), ('Wool', 'Wool'), ('Marble', 'Marble'), ('Cloth', 'Cloth'), ('Suede', 'Suede')], default='Wood', max_length=10),
        ),
    ]
