# Generated by Django 4.0.3 on 2022-03-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_furnitures_description_furnitures_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitures',
            name='img',
            field=models.ImageField(default='upload images', upload_to=''),
        ),
    ]
