# Generated by Django 4.0.3 on 2022-03-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_furnitures_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnitures',
            name='img',
            field=models.ImageField(default='upload images', upload_to='images'),
        ),
    ]
