# Generated by Django 3.2.5 on 2022-03-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_furnitures_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnitures',
            name='img',
            field=models.ImageField(default='../media/images/chaise-avec-accoudoirs-bleue-1000-13-39-210082_1.png', upload_to='images'),
        ),
    ]
